version: "3.1"

services: 
  db: 
    image: postgres:10.2-alpine
    environment:
      POSTGRES_PASSWORD: 123123
      POSTGRES_USER: root
      POSTGRES_DB: test
    ports: 
      - "5432:5432"
  app: 
    image: 'node:8.9.1-alpine'
    working_dir: /backend
    command: yarn dev
    volumes:
      - '.:/backend'
    ports:
      - '3000:80'
    environment:
      PORT: 80
      DATABASE_URL: postgres://root:123123@db:5432/test
      PASSWORD_SALT: salt_for_password
    links:
      - db
    depends_on:
      - db  
    
