version: "3.6"

services:
  backend:
    image: node:9.11.1-alpine
    working_dir: /backend
    command: npm run dev
    volumes:
      - "./server:/backend/server"
      - "./node_modules:/backend/node_modules"
      - "./package.json:/backend/package.json"
    ports:
      - '3000:3000'
    environment:
      MONGODB_URI: mongodb://mongo:27017/mfc-admin
    links:
      - mongo
    depends_on:
      - mongo
  mongo:
    image: mongo:3.4.14-jessie
    volumes:
      - "./data/mongodb:/data"
    ports:
      - '27017:27017'
    logging:
      driver: none

